### ISSUE TITLE
Make setup sdk calls Async

### ISSUE THREAD

**Issue by kolevv** [TehThreeMusketeers/MobileApp#3]
Need to change the set access token and setup sdk calls in setup photon activity Async, as shown [here](https://docs.particle.io/reference/android/#blocking-apis-ftw), otherwise Android might not allow blocking calls from UI thread.

**Comment by OfficialSoaresO** [comment]
Also done I believe

**Comment by kolevv** [comment]
I couldn't find a commit that fixes this - issue reopened, i'll work upload a branch that fixes this later today

**Comment by kolevv** [comment]
Now fixed in the Async branch.
