### ISSUE TITLE
API call to send Firebase token to server.

### ISSUE THREAD

**Issue by kolevv** [TehThreeMusketeers/MobileApp#48]
Need an API call to send the Firebase token to the server so we can receive notifications. The endpoints aren't implemented yet, but there is a TODO in the APICalls class that explains what they (should) be. Implement this as soon as the endpoints exist on the server.

**Comment by OfficialSoaresO** [comment]
Already implemented, waiting on endpoints, once we have them I can tweak if necessary but structure is there

**Comment by kolevv** [comment]
This works fine. It's the logic of where I call it that's the issue. Closing this one and opening a new one.
